### ISSUE TITLE
It’s possible control the playhead of cdj from the protocol?

### ISSUE THREAD

**Issue by DubbyLabby** [brunchboy/dysentery#11]
So sending the proper message over lan could gain “deck playhead” control and scratch it like if you were using the regular platter encoder in the cdj?

I ask this due from pure curiosity since I wonder over the time how powerfull and integrated is the protocol itself.

Thx

**Comment by brunchboy** [comment]
No, the protocol doesn’t have anything like that, it is completely outside the intention and scope. It is just a basic synchronization protocol to do what the CDJs can do. It is rather limited in scope, and shows evidence of having grown without careful thought. You should read the [Analysis paper](https://github.com/brunchboy/dysentery/blob/master/doc/Analysis.pdf) which explains it all completely and in detail.

**Comment by jan2000** [comment]
> No, the protocol doesn’t have anything like that, remote control is completely outside the intention and scope.

Well, that is not completely true. At least some playback controls over the network are possible for the CDJ2000nxs2 or XDJ1000mk2 in combination with the DDJ-SP1 or DDJ-XP1. See:

http://docs.pioneerdj.com/Manuals/XDJ_1000MK2_MultiPlayerSeries_DJController_HardwareDiagram_En_addendum/?page=2

**Comment by brunchboy** [comment]
Interesting. If you can figure out the relevant network packets, pull requests would be most welcome!

**Comment by jan2000** [comment]
Yes I am interested in those packets as well. Unfortunately I also do not have access to these controllers.

**Comment by brunchboy** [comment]
Well, I’ll reopen the issue and mark it as Help Wanted, in case anyone who does, and who can muck around in Wireshark, is willing to take a look.

**Comment by brunchboy** [comment]
Actually, reviewing that diagram, it shows that the controller is connected to the player via USB, not via the network, so I am back to believing this is not possible.

**Comment by jan2000** [comment]
The controller is connected to one player via USB, however it controls the other players over the network. "Furthermore, one DJ controller can be used to control up to four players connected with PRO DJ LINK."

**Comment by brunchboy** [comment]
Huh. Well, maybe someday someone with such players will take network captures and figure that out. There is nothing whatsoever I can do without them even if I wanted to.

**Comment by brunchboy** [comment]
And, sorry, @jan2000, I did not mean to sound at all dismissive… I am exhausted from putting in far too many hours this weekend on dysentery, Beat Link, and Beat Link Trigger… I should have slept and rested a lot more, but I was making so much progress! 😫 But also, since there is no way for me to make any progress on this issue, and nobody else has taken the initiative to do so, I don’t want it sitting around distracting from the issues that are blocking current and desired use cases.

As an aside, I have to admit I am rather baffled about _why_ Pioneer supports this. If you want to use a controller, why spend money and space on CDJs? Just use it with your laptop which is more flexible and configurable and gets better over time.
